import { ref, watch, onBeforeUnmount } from 'vue';
import { socket,request,members,iceServers,roomId } from './useRoom';
export function useVoice(){
 const active=ref(false),muted=ref(false),voiceError=ref('');let stream=null;const peers=new Map();
 function remove(id){const p=peers.get(id);if(p){p.pc.close();p.audio.srcObject=null;p.audio.remove();peers.delete(id);}}
 function make(id){if(peers.has(id))return peers.get(id);const pc=new RTCPeerConnection({iceServers:iceServers.value});const audio=document.createElement('audio');audio.autoplay=true;document.body.append(audio);const p={pc,audio,candidates:[]};peers.set(id,p);for(const track of stream.getTracks())pc.addTrack(track,stream);pc.ontrack=e=>{audio.srcObject=e.streams[0];audio.play().catch(()=>voiceError.value='Click Resume voice to allow audio.');};pc.onicecandidate=e=>{if(e.candidate)request('voice:signal',{to:id,type:'ice-candidate',payload:e.candidate.toJSON()}).catch(()=>{});};pc.onconnectionstatechange=()=>{if(pc.connectionState==='failed')voiceError.value='A voice connection failed. Rejoin voice or configure a TURN relay for this network.';};return p;}
 async function sync(){if(!active.value)return;const ids=members.value.filter(m=>m.voice&&m.socketId!==socket.id).map(m=>m.socketId);for(const id of peers.keys())if(!ids.includes(id))remove(id);for(const id of ids){if(peers.has(id))continue;const p=make(id);if(socket.id<id){try{await p.pc.setLocalDescription(await p.pc.createOffer());await request('voice:signal',{to:id,type:'offer',payload:p.pc.localDescription});}catch(e){voiceError.value=e.message;remove(id);}}}}
 async function signal({from,type,payload}){if(!active.value||!stream)return;try{const p=make(from);if(type==='ice-candidate'){if(p.pc.remoteDescription)await p.pc.addIceCandidate(payload);else p.candidates.push(payload);}else{await p.pc.setRemoteDescription(payload);for(const candidate of p.candidates)await p.pc.addIceCandidate(candidate);p.candidates=[];if(type==='offer'){await p.pc.setLocalDescription(await p.pc.createAnswer());await request('voice:signal',{to:from,type:'answer',payload:p.pc.localDescription});}}}catch(e){voiceError.value='Voice could not connect. Try leaving and rejoining voice.';}}
 async function start(){voiceError.value='';try{if(!navigator.mediaDevices?.getUserMedia)throw new Error('Voice needs HTTPS or localhost and microphone permission.');stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true},video:false});active.value=true;muted.value=false;await request('voice:state',{enabled:true});await sync();}catch(e){stop();voiceError.value=e.name==='NotAllowedError'?'Microphone permission was denied. Allow it in your browser to join voice.':e.message;}}
 function stop(){active.value=false;stream?.getTracks().forEach(t=>t.stop());stream=null;for(const id of peers.keys())remove(id);if(socket.connected)request('voice:state',{enabled:false}).catch(()=>{});}
 function toggleMute(){muted.value=!muted.value;stream?.getAudioTracks().forEach(t=>t.enabled=!muted.value);}
 function resume(){for(const p of peers.values())p.audio.play().catch(()=>{});voiceError.value='';}
 const unwatch=watch(members,sync,{deep:true});const unroom=watch(roomId,()=>{if(active.value)stop();});socket.on('voice:signal',signal);socket.on('disconnect',stop);
 onBeforeUnmount(()=>{stop();unwatch();unroom();socket.off('voice:signal',signal);socket.off('disconnect',stop);});
 return{active,muted,voiceError,start,stop,toggleMute,resume};
}
