<script setup>
import {ref,computed,watch,nextTick,onMounted,onBeforeUnmount} from 'vue';
import {Play,Plus,Link,ArrowUpRight,ArrowRight,Users,MessageCircle,Headphones,Mic,MicOff,Volume2,Send,ChevronDown,ChevronRight,X,Check,Copy,LogOut,Settings2,Radio,Film,Globe,MonitorPlay,Heart,Smile,ExternalLink} from 'lucide-vue-next';
import SyncPlayer from './components/SyncPlayer.vue';
import {profile,partners,room,members,messages,connected,ready,error,request,pickVideo,joinRoom,leaveRoom,updateProfile,switchGuest} from './composables/useRoom';
import {useVoice} from './composables/useVoice';
const voice=useVoice();const {active,muted,voiceError}=voice;
const url=ref(''),busy=ref(false),message=ref(''),chatList=ref(null),dialog=ref(null),dialogElement=ref(null),copied=ref(false),toast=ref(''),filter=ref('All videos'),editName=ref(''),editAvatar=ref(''),mobileTab=ref('watch'),localError=ref(''),videoFormat=ref('Auto'),unread=ref(0),installPrompt=ref(null);let toastTimer;
const navItems=[{id:'watch',label:'Watch',icon:MonitorPlay},{id:'explore',label:'Explore',icon:Film},{id:'chat',label:'Chat',icon:MessageCircle},{id:'people',label:'People',icon:Users}];
function selectTab(id){mobileTab.value=id;if(id==='chat')unread.value=0;}
function openPicker(){url.value=room.value?.video.url||'';videoFormat.value=room.value?.video.provider||'Auto';if(!['Auto','Video','HLS','TS','DASH','FLV'].includes(videoFormat.value))videoFormat.value='Auto';dialog.value='pick';}
async function share(){if(!room.value){openPicker();return;}if(navigator.share){try{await navigator.share({title:'Watch together on Afterglow',url:roomLink.value});return;}catch(e){if(e.name==='AbortError')return;}}dialog.value='invite';}
function captureInstall(event){event.preventDefault();installPrompt.value=event;}
async function install(){if(installPrompt.value){await installPrompt.value.prompt();installPrompt.value=null;}else dialog.value='install';}
function viewport(){const v=window.visualViewport;document.documentElement.style.setProperty('--app-height',`${v?.height||window.innerHeight}px`);document.documentElement.classList.toggle('keyboard-open',!!v&&window.innerHeight-v.height>140);}
onMounted(()=>{viewport();window.visualViewport?.addEventListener('resize',viewport);window.addEventListener('resize',viewport);window.addEventListener('beforeinstallprompt',captureInstall);});
const avatars=['🌙','🪐','🍿','🦊','🐸','👾','🐻','🌻'];
const videos=[
 {title:'Big Buck Bunny',subtitle:'A little mischief. A lot of heart.',tag:'Animation',provider:'Video',length:'9:56',image:'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=900&q=85',url:'https://storage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',color:'forest'},
 {title:'Sintel',subtitle:'An unexpected journey.',tag:'Animation',provider:'YouTube',length:'14:48',image:'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=900&q=85',url:'https://www.youtube.com/watch?v=eRsGyueVLvQ',color:'mountain'},
 {title:'Tears of Steel',subtitle:'A future worth fighting for.',tag:'Sci-fi',provider:'Video',length:'12:14',image:'https://images.unsplash.com/photo-1519608487953-e999c86e7455?auto=format&fit=crop&w=900&q=85',url:'https://storage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',color:'night'}
];
const shown=computed(()=>videos.filter(v=>filter.value==='All videos'||v.tag===filter.value));
const onlineCount=computed(()=>partners.value.filter(p=>p.online).length);
const roomLink=computed(()=>room.value?`${location.origin}/watch/${room.value.roomId}`:'');
const clock=t=>new Date(t).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});
const time=t=>`${Math.floor((t||0)/60)}:${String(Math.floor((t||0)%60)).padStart(2,'0')}`;
function notify(text){toast.value=text;clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.value='',3500);}
async function pick(value=url.value,title){busy.value=true;localError.value='';try{await pickVideo(value,title,title?'Auto':videoFormat.value);url.value='';videoFormat.value='Auto';dialog.value=null;mobileTab.value='watch';notify('Ready to watch. Invite your people.');}catch(e){localError.value=e.message;}finally{busy.value=false;}}
async function join(id){try{await joinRoom(id);mobileTab.value='watch';notify('You’re in. Make yourself at home.');}catch(e){error.value=e.message;notify(e.message);}}
async function leave(){voice.stop();try{await leaveRoom();notify('You left the room.');}catch(e){error.value=e.message;}}
async function send(){if(!message.value.trim())return;const text=message.value;message.value='';try{await request('chat:send',{text});}catch(e){message.value=text;error.value=e.message;notify(e.message);}}
function react(emoji){if(!room.value)return notify('Pick a video to start reacting together.');request('reaction:send',{emoji}).catch(e=>error.value=e.message);}
async function copy(){try{await navigator.clipboard.writeText(roomLink.value);copied.value=true;notify('Watch link copied. Send it to a friend.');setTimeout(()=>copied.value=false,2500);}catch{dialog.value='invite';}}
function edit(){editName.value=profile.value.name;editAvatar.value=profile.value.avatar;dialog.value='profile';}
async function save(){try{await updateProfile(editName.value,editAvatar.value);dialog.value=null;notify('Looking good. Profile updated.');}catch(e){error.value=e.message;notify(e.message);}}
async function newGuest(){try{await switchGuest();dialog.value=null;notify('You’re now watching as a new guest.');}catch(e){error.value=e.message;}}
watch(messages,async(next,previous)=>{if(mobileTab.value!=='chat'&&previous?.length){unread.value+=next.filter(m=>m.kind==='chat'&&m.profile.id!==profile.value.id&&!previous.some(old=>old.id===m.id)).length;}await nextTick();if(chatList.value)chatList.value.scrollTop=chatList.value.scrollHeight;},{deep:true});
watch(mobileTab,async()=>{await nextTick();if(chatList.value)chatList.value.scrollTop=chatList.value.scrollHeight;});
let previousFocus;
watch(dialog,async value=>{if(value){previousFocus=document.activeElement;await nextTick();dialogElement.value?.querySelector('input,button')?.focus();}else previousFocus?.focus();});
function dialogKeys(e){if(e.key==='Escape')dialog.value=null;if(e.key==='Tab'){const all=dialogElement.value?.querySelectorAll('button,input,a,select');if(!all?.length)return;const first=all[0],last=all[all.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}}
onBeforeUnmount(()=>{clearTimeout(toastTimer);window.visualViewport?.removeEventListener('resize',viewport);window.removeEventListener('resize',viewport);window.removeEventListener('beforeinstallprompt',captureInstall);});
</script>
<template>
 <div class="app-shell" :class="['screen-'+mobileTab,{'in-room':room}]">
  <header class="topbar"><a href="/" class="brand" @click.prevent="room?leave():null"><span class="brand-mark"><span></span><Play :size="20" fill="currentColor"/></span>afterglow<span class="brand-dot">.</span></a><div class="topbar-center"><span class="tiny-orb"></span> Good company. Great watching.</div><button class="profile-button" @click="edit"><span class="avatar small">{{profile.avatar}}</span><span>{{profile.name}}</span><ChevronDown :size="15"/></button></header>
  <div class="workspace">
   <aside class="friends-panel">
    <div class="mobile-only screen-intro"><span class="eyebrow accent">GOOD COMPANY</span><h1>Your people</h1><p>One tap away from your next watch night.</p></div>
    <div class="nav-label">YOUR SPACE</div><button class="lounge-nav" @click="room?leave():null"><MonitorPlay :size="19"/> Watch lounge <span class="active-line"></span></button>
    <div class="friends-heading"><span>WATCH PARTNERS</span><span class="count">{{onlineCount}}</span></div>
    <div v-if="!partners.length" class="friends-empty"><div class="friends-illustration"><Users :size="27"/></div><h3>Better with friends</h3><p>Share a watch link. Anyone who joins appears here, ready for the next movie night.</p><button class="text-button" @click="room?dialog='invite':dialog='pick'">{{room?'Invite a friend':'Start your first room'}} <ArrowRight :size="15"/></button></div>
    <div v-else class="friend-list"><div v-for="f in partners" :key="f.id" class="friend"><div class="avatar friend-avatar">{{f.avatar||'🌙'}}<i :class="{online:f.online}"/></div><div class="friend-info"><strong>{{f.name}}</strong><span>{{f.online?(f.video?`Watching ${f.video.provider} · ${time(f.time)}`:'Hanging out'):'Offline'}}</span><button v-if="f.roomId&&f.roomId!==room?.roomId" class="friend-join" @click="join(f.roomId)">Join room <ArrowUpRight :size="13"/></button><span v-else-if="f.roomId&&f.roomId===room?.roomId" class="with-you">Watching with you</span></div></div></div>
    <div class="sidebar-bottom"><div class="sidebar-note"><span>✦</span><p>Distance is just a detail.<br/>Make a night of it.</p></div><div class="connection"><i :class="{online:connected}"/>{{connected?'All systems cozy':'Reconnecting…'}}<span>v1.0</span></div></div>
   </aside>
   <main class="watch-main">
    <div class="page-heading"><div><div class="eyebrow accent">{{room?'YOUR SHARED SCREEN':'PULL UP A SEAT'}}</div><h1>{{room?'A little closer, together.':'Your watch lounge'}}<span v-if="!room" class="heading-star">✳</span></h1><p>{{room?'Press play. Everyone stays in the same moment.':'Something good on. Your favorite people around.'}}</p></div><button class="button secondary new-video" @click="openPicker"><Plus :size="17"/>{{room?'Change video':'Add a video'}}</button></div>
    <form class="url-bar" @submit.prevent="pick()"><Link :size="19"/><input v-model="url" aria-label="Video URL" placeholder="Paste a YouTube, Vimeo, or video link…" required type="url"/><span class="url-hint">Your next watch starts here</span><button type="submit" :disabled="busy||!ready" aria-label="Watch video"><span>{{busy?'Loading…':'Let’s watch'}}</span><ArrowRight :size="18"/></button></form>
    <div v-if="localError||error" class="error-banner" role="alert"><span>{{localError||error}}</span><button class="icon-button" aria-label="Dismiss error" @click="localError='';error=''"><X :size="16"/></button></div>
    <SyncPlayer @pick="openPicker" @invite="share"/>
    <div class="below-player"><div class="watch-status"><span class="status-symbol"><Users :size="18"/></span><div><strong>{{room?room.video.title:'The room is yours'}}</strong><span>{{room?`${members.length} ${members.length===1?'person':'people'} here · Everyone can control playback`:'Choose a video and we’ll take care of the rest.'}}</span></div></div><div class="reaction-buttons"><button v-for="emoji in ['❤️','😂','🔥','👏','😮']" :key="emoji" :aria-label="'React '+emoji" @click="react(emoji)">{{emoji}}</button></div><button v-if="room" class="icon-button leave-button" aria-label="Leave room" @click="leave"><LogOut :size="18"/></button></div>
    <div class="mobile-only watch-tools"><button @click="share"><Link :size="19"/><span>{{room?'Invite friends':'Start a room'}}</span><ChevronRight :size="16"/></button><button @click="selectTab('chat')"><MessageCircle :size="19"/><span>Room chat</span><span class="count">{{members.length}}</span></button><button :disabled="!room" @click="active?voice.toggleMute():voice.start()"><MicOff v-if="muted" :size="19"/><Headphones v-else :size="19"/><span>{{active?(muted?'Unmute microphone':'Mute microphone'):'Join voice'}}</span><span class="voice-dot" :class="{enabled:active}"/></button><p v-if="voiceError" role="alert">{{voiceError}}</p></div>
    <div class="mobile-only mobile-formats"><span>MADE FOR MOVIE NIGHTS</span><p>YouTube · Vimeo · MP4 · HLS · TS · DASH</p></div>
    <section class="discover"><div class="section-heading"><div><h2>{{room?'Up for something else?':'A little inspiration'}}</h2><p>Pick a short film. Make it a shared moment.</p></div><div class="filters"><button v-for="f in ['All videos','Animation','Sci-fi']" :class="{selected:filter===f}" @click="filter=f">{{f}}</button></div></div><div class="video-grid"><button v-for="v in shown" :key="v.title" class="video-card" @click="pick(v.url,v.title)"><div class="thumbnail" :class="v.color"><img :src="v.image" :alt="v.title+' mood artwork'" loading="lazy"/><div class="thumbnail-shade"></div><span class="provider-tag"><Play :size="12" fill="currentColor"/>{{v.provider==='YouTube'?'YouTube':'Short film'}}</span><span class="thumbnail-title">{{v.title}}</span><span class="card-play"><Play :size="20" fill="currentColor"/></span><span class="duration">{{v.length}}</span></div><div class="card-description"><div><h3>{{v.title}}</h3><p>{{v.subtitle}}</p></div><ArrowUpRight :size="18"/></div></button></div><button class="button secondary mobile-only explore-add" @click="openPicker"><Plus :size="18"/> Watch your own link</button></section>
    <footer class="main-footer"><span><Link :size="13"/> One link. No downloads. Just together.</span><span>Made for your kind of night <span class="footer-star">✦</span></span></footer>
   </main>
   <aside class="chat-panel"><div class="chat-header"><div><MessageCircle :size="18"/><h2>Room chat</h2></div><span class="count">{{members.length}}</span></div><div class="room-presence"><div class="member-avatars"><span v-if="!room" class="avatar small">{{profile.avatar}}</span><span v-for="m in members.slice(0,5)" :key="m.socketId" class="avatar small" :title="m.name">{{m.avatar}}</span></div><div><strong>{{room?(members.length>1?'The gang’s here':'You’re the first one here'):'A spot for everyone'}}</strong><span>{{room?'Good times start with an invite.':'Bring your people along.'}}</span></div></div><button class="invite-button" @click="room?dialog='invite':dialog='pick'"><Link :size="16"/>{{room?'Invite friends':'Pick a video to invite friends'}}<Plus :size="15"/></button>
    <div ref="chatList" class="chat-messages" aria-live="polite" aria-label="Chat messages"><div v-if="!messages.length" class="chat-empty"><span class="chat-spark">✳</span><h3>Let the good times roll.</h3><p>The hot takes, the plot twists,<br/>the “wait, rewind that.”<br/>They all happen here.</p><span class="chat-empty-rule"></span><span>YOUR GROUP CHAT, WITH A PLAY BUTTON.</span></div><template v-for="m in messages" :key="m.id"><div v-if="m.kind==='system'" class="system-message"><span>{{m.text}}</span><time>{{clock(m.at)}}</time></div><div v-else class="chat-message"><span class="avatar small">{{m.profile.avatar}}</span><div><div class="message-meta"><strong>{{m.profile.id===profile.id?'You':m.profile.name}}</strong><time>{{clock(m.at)}}</time></div><p>{{m.text}}</p></div></div></template></div>
    <div class="chat-bottom"><form class="chat-input" @submit.prevent="send"><input v-model="message" maxlength="1000" aria-label="Chat message" :placeholder="room?'Say something nice…':'Your chat starts with a video'" :disabled="!room||!ready"/><button type="submit" aria-label="Send message" :disabled="!message.trim()||!room"><Send :size="18"/></button></form><div class="voice-card"><div class="voice-copy"><span class="voice-icon"><Headphones :size="18"/></span><div><strong>{{active?'You’re in voice':'Better with your voice'}}</strong><span>{{active?(muted?'Microphone muted':'Mic on · Echo cancellation on'):'Laugh out loud. Together.'}}</span></div></div><button v-if="!active" class="voice-join" :disabled="!room" @click="voice.start"><Mic :size="15"/> Join voice</button><div v-else class="voice-actions"><button class="button secondary" @click="voice.toggleMute"><MicOff v-if="muted" :size="16"/><Mic v-else :size="16"/>{{muted?'Unmute':'Mute'}}</button><button class="icon-button" aria-label="Leave voice" @click="voice.stop"><LogOut :size="17"/></button></div><p v-if="voiceError" class="voice-error" role="alert">{{voiceError}}<button v-if="voiceError.includes('Resume')" @click="voice.resume">Resume voice</button></p></div><div class="private-note"><Headphones :size="12"/> A little room for your people.</div></div>
   </aside>
  </div>
  <button v-if="room&&['explore','people'].includes(mobileTab)" class="mobile-only mini-player" @click="selectTab('watch')"><span class="mini-art"><Play :size="20" fill="currentColor"/></span><span><strong>{{room.video.title}}</strong><small>{{room.playbackState==='playing'?'Playing':'Paused'}} · {{members.length}} watching</small></span><ChevronRight :size="19"/></button>
  <nav class="mobile-only bottom-nav" aria-label="Main navigation"><button v-for="item in navItems" :key="item.id" :class="{selected:mobileTab===item.id}" :aria-current="mobileTab===item.id?'page':undefined" @click="selectTab(item.id)"><span><component :is="item.icon" :size="23" :stroke-width="mobileTab===item.id?2.2:1.7"/><b v-if="item.id==='chat'&&unread">{{Math.min(unread,99)}}</b></span>{{item.label}}</button></nav>
  <Transition name="toast"><div v-if="toast" class="toast" role="status"><Check :size="17"/>{{toast}}</div></Transition>
  <div v-if="dialog" class="modal-backdrop" @click.self="dialog=null" @keydown="dialogKeys"><section ref="dialogElement" class="modal" role="dialog" aria-modal="true" :aria-label="dialog==='pick'?'Choose a video':dialog==='invite'?'Invite friends':'Edit your profile'"><button class="modal-close icon-button" aria-label="Close dialog" @click="dialog=null"><X :size="20"/></button>
   <template v-if="dialog==='pick'"><span class="modal-icon"><Film :size="27"/></span><h2>What are we watching?</h2><p>Drop in a video link. We’ll find the right player.</p><form @submit.prevent="pick()"><label for="pick-url">Video link</label><input id="pick-url" v-model="url" type="url" inputmode="url" autocomplete="off" autocapitalize="off" spellcheck="false" required placeholder="Paste your video URL"/><div class="format-picker"><label for="video-format">Video format</label><select id="video-format" v-model="videoFormat"><option value="Auto">Detect automatically</option><option value="Video">MP4 / WebM / native video</option><option value="HLS">HLS (.m3u8)</option><option value="TS">MPEG-TS (.ts / .m2ts)</option><option value="DASH">DASH (.mpd)</option><option value="FLV">FLV</option></select></div><div class="supported"><span>YouTube</span><span>Vimeo</span><span>MP4</span><span>HLS</span><span>TS</span><span>DASH</span></div><p v-if="localError" class="form-error" role="alert">{{localError}}</p><button class="button full" type="submit" :disabled="busy||!ready"><Play :size="17" fill="currentColor"/>{{busy?'Getting ready…':room?'Watch this instead':'Let’s watch together'}}</button></form><span class="modal-hint">Direct video links and supported embeds. Webpages and protected streams may not play.</span></template>
   <template v-else-if="dialog==='invite'"><span class="modal-icon"><Users :size="28"/></span><h2>Save them a seat.</h2><p>Send this link. They’ll join you right here.</p><label for="room-link">Your watch link</label><div class="share-field"><input id="room-link" :value="roomLink" readonly @focus="$event.target.select()"/><button class="icon-button" aria-label="Copy watch link" @click="copy"><Check v-if="copied" :size="19"/><Copy v-else :size="19"/></button></div><button class="button full" @click="copy"><Check v-if="copied" :size="17"/><Link v-else :size="17"/>{{copied?'Copied!':'Copy invite link'}}</button><div class="invite-details"><span><Check :size="15"/> No account needed</span><span><Check :size="15"/> Up to 8 people</span></div></template>
   <template v-else-if="dialog==='install'"><span class="modal-icon"><MonitorPlay :size="27"/></span><h2>A home for movie night.</h2><p>Add Afterglow to your Home Screen for a full-screen app experience.</p><ol class="install-steps"><li>Open this app in Safari on your iPhone.</li><li>Tap the Share button.</li><li>Choose “Add to Home Screen”, then tap Add.</li></ol><p class="modal-hint">On Android, use Install app in your browser menu. Watching together needs an internet connection.</p></template>
   <template v-else><span class="profile-preview avatar">{{editAvatar}}</span><h2>Make yourself at home.</h2><p>A familiar face for your next watch night.</p><form @submit.prevent="save"><label for="guest-name">Your name</label><input id="guest-name" v-model="editName" maxlength="24" required/><label>Pick your avatar</label><div class="avatar-picker"><button v-for="a in avatars" :class="{chosen:editAvatar===a}" type="button" :aria-label="'Select avatar '+a" @click="editAvatar=a">{{a}}</button></div><button class="button full" type="submit">Save profile <Check :size="17"/></button></form><button class="button secondary full install-button" @click="install"><Plus :size="18"/> Add to Home Screen</button><button class="text-button new-guest" @click="newGuest">Use a new guest identity</button><span class="modal-hint">A new identity clears your saved partners on this browser.</span></template>
  </section></div>
 </div>
</template>
