<script setup>
import {ref,computed,watch,nextTick,onMounted,onBeforeUnmount} from 'vue';
import {Play,Plus,Link,ArrowUpRight,ArrowRight,Users,MessageCircle,Headphones,Mic,MicOff,Send,ChevronDown,ChevronRight,X,Check,Copy,LogOut,Settings2,Film,Globe,MonitorPlay,HardDrive,Youtube,History} from 'lucide-vue-next';
import SyncPlayer from './components/SyncPlayer.vue';
import {profile,partners,room,members,messages,connected,ready,error,request,pickVideo,joinRoom,leaveRoom,updateProfile,switchGuest} from './composables/useRoom';
import {useVoice} from './composables/useVoice';
const voice=useVoice();const {active,muted,voiceError}=voice;
const url=ref(''),busy=ref(false),message=ref(''),chatList=ref(null),dialog=ref(null),dialogElement=ref(null),copied=ref(false),toast=ref(''),filter=ref('All videos'),editName=ref(''),editAvatar=ref(''),mobileTab=ref('watch'),localError=ref(''),videoFormat=ref('Auto'),unread=ref(0),installPrompt=ref(null);let toastTimer;
const navItems=[{id:'watch',label:'Watch',icon:MonitorPlay},{id:'chat',label:'Chat',icon:MessageCircle}];
const player=ref(null),showAvatars=ref(true),selectedPartner=ref(null),pickerSource=ref('');
const recentVideos=ref(readHistory());
function readHistory(){try{const value=JSON.parse(localStorage.getItem('afterglow.history')||'[]');return Array.isArray(value)?value.filter(v=>typeof v.url==='string'&&typeof v.title==='string').slice(0,8):[];}catch{return [];}}
function rememberVideo(){const video=room.value?.video;if(!video)return;recentVideos.value=[{url:video.url,title:video.title,provider:video.provider},...recentVideos.value.filter(v=>v.url!==video.url)].slice(0,8);try{localStorage.setItem('afterglow.history',JSON.stringify(recentVideos.value));}catch{}}
watch(()=>room.value?.video.url,rememberVideo);
async function people(person=null){await player.value?.exitFullscreen();selectedPartner.value=person;dialog.value='people';}
function chooseSource(source){openPicker();pickerSource.value=source;url.value='';videoFormat.value=source==='Web page / iframe'?'Embed':'Auto';}
async function playerChat(){await player.value?.exitFullscreen();selectTab(mobileTab.value==='chat'?'watch':'chat');}
async function playerInvite(){await player.value?.exitFullscreen();share();}
async function playerLeave(){await player.value?.exitFullscreen();leave();}
function selectTab(id){mobileTab.value=id;if(id==='chat')unread.value=0;}
function openPicker(){pickerSource.value='';url.value=room.value?.video.url||'';videoFormat.value=room.value?.video.provider||'Auto';if(!['Auto','Video','HLS','TS','DASH','FLV','Embed'].includes(videoFormat.value))videoFormat.value='Auto';dialog.value='pick';}
async function share(){if(!room.value){openPicker();return;}if(navigator.share){try{await navigator.share({title:'Watch together on Afterglow',url:roomLink.value});return;}catch(e){if(e.name==='AbortError')return;}}dialog.value='invite';}
function captureInstall(event){event.preventDefault();installPrompt.value=event;}
async function install(){if(installPrompt.value){await installPrompt.value.prompt();installPrompt.value=null;}else dialog.value='install';}
function viewport(){const v=window.visualViewport;document.documentElement.style.setProperty('--app-height',`${v?.height||window.innerHeight}px`);document.documentElement.classList.toggle('keyboard-open',!!v&&window.innerHeight-v.height>140);}
onMounted(()=>{viewport();window.visualViewport?.addEventListener('resize',viewport);window.addEventListener('resize',viewport);window.addEventListener('beforeinstallprompt',captureInstall);});
const avatars=['🌙','🪐','🍿','🦊','🐸','👾','🐻','🌻'];
const videos=[
 {title:'Big Buck Bunny',subtitle:'A little mischief. A lot of heart.',tag:'Animation',provider:'Video',length:'9:56',image:'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=900&q=85',url:'https://storage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',color:'forest'},
 {title:'Sintel',subtitle:'An unexpected journey.',tag:'Animation',provider:'YouTube',length:'14:48',image:'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=900&q=85',url:'https://www.youtube.com/watch?v=eRsGyueVLvQ',color:'mountain'},
 {title:'Tears of Steel',subtitle:'A future worth fighting for.',tag:'Sci-fi',provider:'Video',length:'12:14',image:'https://images.unsplash.com/photo-1519608487953-e999c86e7455?auto=format&fit=crop&w=900&q=85',url:'https://storage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',color:'night'}
];
const shown=computed(()=>videos.filter(v=>filter.value==='All videos'||v.tag===filter.value));
const onlineCount=computed(()=>partners.value.filter(p=>p.online).length);
const roomLink=computed(()=>room.value?`${location.origin}/watch/${room.value.roomId}`:'');
const clock=t=>new Date(t).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});
const time=t=>`${Math.floor((t||0)/60)}:${String(Math.floor((t||0)%60)).padStart(2,'0')}`;
function notify(text){toast.value=text;clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.value='',3500);}
async function pick(value=url.value,title,format){busy.value=true;localError.value='';try{await pickVideo(value,title,format||(title?'Auto':videoFormat.value));url.value='';videoFormat.value='Auto';dialog.value=null;mobileTab.value='watch';notify('Ready to watch. Invite your people.');}catch(e){localError.value=e.message;}finally{busy.value=false;}}
async function nextEpisode(){const target=room.value?.video?.next;if(!target)return;busy.value=true;localError.value='';try{await pickVideo(target,null,'Auto');notify('Next episode. Same couch, new chapter.');}catch(e){localError.value=e.message;notify(e.message);}finally{busy.value=false;}}
async function join(id){try{await joinRoom(id);mobileTab.value='watch';notify('You’re in. Make yourself at home.');}catch(e){error.value=e.message;notify(e.message);}}
async function leave(){voice.stop();try{await leaveRoom();notify('You left the room.');}catch(e){error.value=e.message;}}
async function send(){if(!message.value.trim())return;const text=message.value;message.value='';try{await request('chat:send',{text});}catch(e){message.value=text;error.value=e.message;notify(e.message);}}
function react(emoji){if(!room.value)return notify('Pick a video to start reacting together.');request('reaction:send',{emoji}).catch(e=>error.value=e.message);}
async function copy(){try{await navigator.clipboard.writeText(roomLink.value);copied.value=true;notify('Watch link copied. Send it to a friend.');setTimeout(()=>copied.value=false,2500);}catch{dialog.value='invite';}}
function edit(){editName.value=profile.value.name;editAvatar.value=profile.value.avatar;dialog.value='profile';}
async function save(){try{await updateProfile(editName.value,editAvatar.value);dialog.value=null;notify('Looking good. Profile updated.');}catch(e){error.value=e.message;notify(e.message);}}
async function newGuest(){try{await switchGuest();dialog.value=null;notify('You’re now watching as a new guest.');}catch(e){error.value=e.message;}}
watch(messages,async(next,previous)=>{if(mobileTab.value!=='chat'&&previous?.length){unread.value+=next.filter(m=>m.kind==='chat'&&m.profile.id!==profile.value.id&&!previous.some(old=>old.id===m.id)).length;}await nextTick();if(chatList.value)chatList.value.scrollTop=chatList.value.scrollHeight;},{deep:true});
watch(mobileTab,async()=>{await nextTick();if(chatList.value)chatList.value.scrollTop=chatList.value.scrollHeight;});
let previousFocus;
watch(dialog,async value=>{if(value){previousFocus=document.activeElement;await nextTick();dialogElement.value?.querySelector('input,button')?.focus();}else previousFocus?.focus();});
function dialogKeys(e){if(e.key==='Escape')dialog.value=null;if(e.key==='Tab'){const all=dialogElement.value?.querySelectorAll('button,input,a,select');if(!all?.length)return;const first=all[0],last=all[all.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}}
onBeforeUnmount(()=>{clearTimeout(toastTimer);window.visualViewport?.removeEventListener('resize',viewport);window.removeEventListener('resize',viewport);window.removeEventListener('beforeinstallprompt',captureInstall);});
</script>
<template>
 <div class="app-shell" :class="['screen-'+mobileTab,{'in-room':room}]">
  <header class="topbar"><a href="/" class="brand" @click.prevent="room?leave():null"><span class="brand-mark"><span></span><Play :size="20" fill="currentColor"/></span>afterglow<span class="brand-dot">.</span></a><div class="topbar-center"><span class="tiny-orb" :class="{offline:!connected}"></span>{{connected?(room?'Watching together':'Ready when you are'):'Reconnecting…'}}</div><button class="profile-button" aria-label="Edit profile" @click="edit"><span class="avatar small">{{profile.avatar}}</span><span>{{profile.name}}</span><ChevronDown :size="15"/></button></header>
  <div class="workspace">
   <aside class="friends-panel">

    <button class="lounge-nav" @click="room?leave():null"><MonitorPlay :size="19"/> Watch lounge <span class="active-line"></span></button>
    <div class="friends-heading"><span>Your people</span><span class="count">{{onlineCount}}</span></div>
    <div v-if="!partners.length" class="friends-empty"><div class="friends-illustration"><Users :size="27"/></div><h3>Better with friends</h3><p>Share a watch link. Anyone who joins appears here, ready for the next movie night.</p><button class="text-button" @click="room?dialog='invite':dialog='pick'">{{room?'Invite a friend':'Start your first room'}} <ArrowRight :size="15"/></button></div>
    <div v-else class="friend-list"><div v-for="f in partners" :key="f.id" class="friend"><div class="avatar friend-avatar">{{f.avatar||'🌙'}}<i :class="{online:f.online}"/></div><div class="friend-info"><strong>{{f.name}}</strong><span>{{f.online?(f.video?`Watching ${f.video.provider} · ${time(f.time)}`:'Hanging out'):'Offline'}}</span><button v-if="f.roomId&&f.roomId!==room?.roomId" class="friend-join" @click="join(f.roomId)">Join room <ArrowUpRight :size="13"/></button><span v-else-if="f.roomId&&f.roomId===room?.roomId" class="with-you">Watching with you</span></div></div></div>
    <div class="sidebar-bottom"><div class="connection"><i :class="{online:connected}"/>{{connected?'All systems cozy':'Reconnecting…'}}<span>v1.0</span></div></div>
   </aside>
   <main class="watch-main">
    <div class="page-heading"><div><h1>{{room?'Watch room':'Your watch lounge'}}</h1><p>{{room?'Press play. Everyone stays in the same moment.':'Something good on. Your favorite people around.'}}</p></div><div class="heading-actions"><button v-if="room?.video.next" class="button secondary next-episode" @click="nextEpisode">Next episode <ArrowRight :size="15"/></button><button class="button secondary new-video" @click="openPicker"><Plus :size="17"/>{{room?'Change video':'Add a video'}}</button></div></div>
    <form v-if="!room" class="url-bar" @submit.prevent="pick()"><Link :size="19"/><input v-model="url" aria-label="Video URL" placeholder="Paste a YouTube, Drive, or video link…" required type="url"/><button type="submit" :disabled="busy||!ready" aria-label="Watch video"><span>{{busy?'Loading…':'Let’s watch'}}</span><ArrowRight :size="18"/></button></form>
    <div v-if="localError||error" class="error-banner" role="alert"><span>{{localError||error}}</span><button class="icon-button" aria-label="Dismiss error" @click="localError='';error=''"><X :size="16"/></button></div>
    <SyncPlayer ref="player" @pick="openPicker" @invite="share">
     <template #party>
      <div v-if="room" class="mobile-only party-toolbar"><button class="party-action leave-party" aria-label="Leave room" @click.stop="playerLeave"><LogOut :size="20"/></button><button class="party-action" :class="{muted:!active||muted}" :aria-label="active?(muted?'Unmute microphone':'Mute microphone'):'Join voice'" @click.stop="active?voice.toggleMute():voice.start()"><MicOff v-if="!active||muted" :size="21"/><Mic v-else :size="21"/></button><button class="party-action" aria-label="Change video" @click.stop="player.exitFullscreen().then(openPicker)"><Plus :size="23"/></button><button class="party-action party-chat" :aria-label="mobileTab==='chat'?'Show Watch':'Show Chat'" @click.stop="playerChat"><MessageCircle :size="22"/></button></div>
      <div v-if="room" class="mobile-only party-avatars"><template v-if="showAvatars"><button v-for="m in members.slice(0,5)" :key="m.socketId" class="party-avatar" :aria-label="m.name+' · room people and settings'" @click.stop="people()"><span>{{m.avatar}}</span><MicOff v-if="m.id===profile.id?(!active||muted):!m.voice" :size="13" class="avatar-mic"/></button></template><button class="party-avatar invite-avatar" aria-label="Invite friends" @click.stop="playerInvite"><Plus :size="24"/></button><button v-if="!showAvatars" class="party-avatar" aria-label="People and settings" @click.stop="people()"><Users :size="21"/></button></div>
     </template>
    </SyncPlayer>
    <div class="mobile-only mobile-watch-content">
     <section class="recent-people"><div class="mobile-section-heading"><h2>Recent people</h2><button class="icon-button" aria-label="People and settings" @click="people()"><Settings2 :size="20"/></button></div><div class="people-strip"><button class="recent-person" @click="people()"><span class="avatar">{{profile.avatar}}</span><span>You</span></button><button v-for="f in partners" :key="f.id" class="recent-person" @click="people(f)"><span class="avatar friend-avatar">{{f.avatar||'🌙'}}<i :class="{online:f.online}"/></span><span>{{f.name}}</span></button><button class="recent-person" @click="share"><span class="invite-person"><Plus :size="25"/></span><span>Invite</span></button></div></section>
     <section v-if="recentVideos.length" class="recent-videos"><div class="mobile-section-heading"><h2>Watch again</h2><History :size="20"/></div><div class="history-strip"><button v-for="v in recentVideos" :key="v.url" class="history-video" @click="pick(v.url,v.title,v.provider==='Embed'?'Embed':'Auto')"><span class="history-art"><Youtube v-if="v.provider==='YouTube'" :size="32"/><HardDrive v-else-if="v.provider==='Drive'" :size="32"/><Film v-else :size="32"/><span>{{v.provider==='Drive'?'Google Drive':v.provider}}</span></span><strong>{{v.title}}</strong></button></div></section>
     <section class="video-sources"><div class="mobile-section-heading"><h2>Start watching</h2></div><div class="source-grid"><button @click="chooseSource('YouTube')"><span class="source-icon youtube-source"><Youtube :size="38"/></span>YouTube</button><button @click="chooseSource('Google Drive')"><span class="source-icon drive-source"><svg viewBox="0 0 48 48" aria-hidden="true"><path fill="#0f9d58" d="M17 5h14L14 35H0z"/><path fill="#fbbc04" d="M31 5l17 30H34L17 5z"/><path fill="#4285f4" d="M0 35h48l-7 12H7z"/></svg></span>Google Drive</button><button @click="chooseSource('Vimeo')"><span class="source-icon vimeo-source"><Play :size="36" fill="currentColor"/></span>Vimeo</button><button @click="chooseSource('Video link')"><span class="source-icon link-source"><Link :size="32"/></span>Video link</button></div></section>
     <button v-if="room?.video.next" class="button secondary full" @click="nextEpisode">Next episode <ArrowRight :size="18"/></button>
     <div class="mobile-link-actions"><button class="text-button mobile-change-video" @click="chooseSource('Web page / iframe')"><Globe :size="18"/> Open a web player</button>
     <button class="text-button mobile-change-video" @click="openPicker"><Plus :size="18"/>{{room?'Change video':'Paste a link'}}</button></div>
     <p v-if="voiceError" class="form-error" role="alert">{{voiceError}}</p>
    </div>
    <div v-if="room" class="below-player"><div class="watch-status"><span class="status-symbol"><Users :size="18"/></span><div><strong>{{room?room.video.title:'The room is yours'}}</strong><span>{{room?`${members.length} ${members.length===1?'person':'people'} here · ${['Drive','Embed'].includes(room.video.provider)?'Manual playback on each device':'Shared playback controls'}`:'Choose a video and we’ll take care of the rest.'}}</span></div></div><div class="reaction-buttons"><button v-for="emoji in ['❤️','😂','🔥','👏','😮']" :key="emoji" :aria-label="'React '+emoji" @click="react(emoji)">{{emoji}}</button></div><button v-if="room" class="icon-button leave-button" aria-label="Leave room" @click="leave"><LogOut :size="18"/></button></div>
    <section class="discover"><div class="section-heading"><div><h2>{{room?'Up for something else?':'A little inspiration'}}</h2><p>Pick a short film. Make it a shared moment.</p></div><div class="filters"><button v-for="f in ['All videos','Animation','Sci-fi']" :class="{selected:filter===f}" @click="filter=f">{{f}}</button></div></div><div class="video-grid"><button v-for="v in shown" :key="v.title" class="video-card" @click="pick(v.url,v.title)"><div class="thumbnail" :class="v.color"><img :src="v.image" :alt="v.title+' mood artwork'" loading="lazy"/><div class="thumbnail-shade"></div><span class="provider-tag"><Play :size="12" fill="currentColor"/>{{v.provider==='YouTube'?'YouTube':'Short film'}}</span><span class="thumbnail-title">{{v.title}}</span><span class="card-play"><Play :size="20" fill="currentColor"/></span><span class="duration">{{v.length}}</span></div><div class="card-description"><div><h3>{{v.title}}</h3><p>{{v.subtitle}}</p></div><ArrowUpRight :size="18"/></div></button></div></section>
    <footer class="main-footer"><span><Link :size="13"/> One link. No downloads. Just together.</span><span>Made for your kind of night <span class="footer-star">✦</span></span></footer>
   </main>
   <aside class="chat-panel"><div class="chat-header"><div><MessageCircle :size="18"/><h2>Room chat</h2></div><span class="count">{{members.length}}</span></div><div class="room-presence"><div class="member-avatars"><span v-if="!room" class="avatar small">{{profile.avatar}}</span><span v-for="m in members.slice(0,5)" :key="m.socketId" class="avatar small" :title="m.name">{{m.avatar}}</span></div><div><strong>{{room?(members.length>1?'The gang’s here':'You’re the first one here'):'A spot for everyone'}}</strong><span>{{room?'Good times start with an invite.':'Bring your people along.'}}</span></div></div><button class="invite-button" @click="room?dialog='invite':dialog='pick'"><Link :size="16"/>{{room?'Invite friends':'Pick a video to invite friends'}}<Plus :size="15"/></button>
    <div ref="chatList" class="chat-messages" aria-live="polite" aria-label="Chat messages"><div v-if="!messages.length" class="chat-empty"><MessageCircle class="chat-empty-icon" :size="28"/><h3>Let the good times roll.</h3><p>The hot takes, the plot twists,<br/>the “wait, rewind that.”<br/>They all happen here.</p></div><template v-for="m in messages" :key="m.id"><div v-if="m.kind==='system'" class="system-message"><span>{{m.text}}</span><time>{{clock(m.at)}}</time></div><div v-else class="chat-message"><span class="avatar small">{{m.profile.avatar}}</span><div><div class="message-meta"><strong>{{m.profile.id===profile.id?'You':m.profile.name}}</strong><time>{{clock(m.at)}}</time></div><p>{{m.text}}</p></div></div></template></div>
    <div class="chat-bottom"><form class="chat-input" @submit.prevent="send"><input v-model="message" maxlength="1000" aria-label="Chat message" :placeholder="room?'Send party message':'Your chat starts with a video'" :disabled="!room||!ready"/><button type="submit" aria-label="Send message" :disabled="!message.trim()||!room"><Send :size="18"/></button></form><div class="voice-card"><div class="voice-copy"><span class="voice-icon"><Headphones :size="18"/></span><div><strong>{{active?'Voice connected':'Voice chat'}}</strong><span>{{active?(muted?'Microphone muted':'Mic on · Echo cancellation on'):'Laugh out loud. Together.'}}</span></div></div><button v-if="!active" class="voice-join" :disabled="!room" @click="voice.start"><Mic :size="15"/> Join voice</button><div v-else class="voice-actions"><button class="button secondary" @click="voice.toggleMute"><MicOff v-if="muted" :size="16"/><Mic v-else :size="16"/>{{muted?'Unmute':'Mute'}}</button><button class="icon-button" aria-label="Leave voice" @click="voice.stop"><LogOut :size="17"/></button></div><p v-if="voiceError" class="voice-error" role="alert">{{voiceError}}<button v-if="voiceError.includes('Resume')" @click="voice.resume">Resume voice</button></p></div></div>
   </aside>
  </div>
  <nav class="mobile-only bottom-nav" aria-label="Main navigation"><button v-for="item in navItems" :key="item.id" :class="{selected:mobileTab===item.id}" :aria-current="mobileTab===item.id?'page':undefined" @click="selectTab(item.id)"><span><component :is="item.icon" :size="23" :stroke-width="mobileTab===item.id?2.2:1.7"/><b v-if="item.id==='chat'&&unread">{{Math.min(unread,99)}}</b></span>{{item.label}}</button></nav>
  <Transition name="toast"><div v-if="toast" class="toast" role="status"><Check :size="17"/>{{toast}}</div></Transition>
  <div v-if="dialog" class="modal-backdrop" @click.self="dialog=null" @keydown="dialogKeys"><section ref="dialogElement" class="modal" role="dialog" aria-modal="true" :aria-label="dialog==='pick'?'Choose a video':dialog==='invite'?'Invite friends':dialog==='people'?'People and settings':'Edit your profile'"><button class="modal-close icon-button" aria-label="Close dialog" @click="dialog=null"><X :size="20"/></button>
   <template v-if="dialog==='pick'"><span class="modal-icon"><Film :size="27"/></span><h2>{{pickerSource==='Google Drive'?'Watch from Google Drive':'What are we watching?'}}</h2><p>{{pickerSource==='Google Drive'?'Paste a video file’s sharing link. Set access to “Anyone with the link” so your friends can watch.':'Drop in a YouTube, Google Drive, Vimeo, or direct video link.'}}</p><form @submit.prevent="pick()"><label for="pick-url">Video link</label><input id="pick-url" v-model="url" type="text" inputmode="url" autocomplete="off" autocapitalize="off" spellcheck="false" required placeholder="Paste a URL or iframe embed code"/><div class="format-picker"><label for="video-format">Video format</label><select id="video-format" v-model="videoFormat"><option value="Auto">Detect automatically</option><option value="Video">Video / audio file (device decoder)</option><option value="HLS">HLS (.m3u8)</option><option value="TS">MPEG-TS (.ts / .m2ts)</option><option value="DASH">DASH (.mpd)</option><option value="FLV">FLV</option><option value="Embed">Web page / iframe (manual playback)</option></select></div><div class="supported"><span>YouTube</span><span>Google Drive</span><span>Vimeo</span><span>MP4</span><span>HLS</span><span>TS</span><span>DASH</span><span>Web pages / iframes</span></div><p v-if="pickerSource==='Google Drive'||/drive.google.com|docs.google.com/.test(url)" class="drive-help">Drive videos open in Google’s player. Everyone can watch and chat, but playback is controlled separately on each device.</p><p v-if="videoFormat==='Embed'||url.trim().startsWith('<')" class="drive-help">Web pages must allow embedding. YouTube and Vimeo use shared controls; other web players use manual playback. If a site refuses to open here, use Open source.</p><details class="format-help"><summary>Which files can I play?</summary><p>MP4, M4V, WebM, MOV, OGG/OGV, MP3, M4A, AAC, WAV, FLAC and Opus use your device’s decoder. HLS, DASH, TS and FLV have dedicated players.</p><p>3GP, AIF, ASF, AVI, MKV, MPA/MPE/MPEG/MPG, QT, RA/RM/RMVB and WMA/WMV are recognized, but many browsers need them converted to MP4 (H.264/AAC) or MP3.</p><p>Archives (ZIP, RAR, 7Z and similar), installers, disk images, PDF, PowerPoint and TIFF are not video. Extract archives first and share the media inside.</p></details><p v-if="localError" class="form-error" role="alert">{{localError}}</p><button class="button full" type="submit" :disabled="busy||!ready"><Play :size="17" fill="currentColor"/>{{busy?'Getting ready…':room?'Watch this instead':'Let’s watch together'}}</button></form><span class="modal-hint">Direct video links and supported embeds. Webpages and protected streams may not play.</span></template>
   <template v-else-if="dialog==='invite'"><span class="modal-icon"><Users :size="28"/></span><h2>Save them a seat.</h2><p>Send this link. They’ll join you right here.</p><label for="room-link">Your watch link</label><div class="share-field"><input id="room-link" :value="roomLink" readonly @focus="$event.target.select()"/><button class="icon-button" aria-label="Copy watch link" @click="copy"><Check v-if="copied" :size="19"/><Copy v-else :size="19"/></button></div><button class="button full" @click="copy"><Check v-if="copied" :size="17"/><Link v-else :size="17"/>{{copied?'Copied!':'Copy invite link'}}</button><div class="invite-details"><span><Check :size="15"/> No account needed</span><span><Check :size="15"/> Up to 8 people</span></div></template>
   <template v-else-if="dialog==='people'"><h2>{{selectedPartner?selectedPartner.name:'People & settings'}}</h2><template v-if="selectedPartner"><div class="profile-preview avatar">{{selectedPartner.avatar}}</div><p>{{selectedPartner.online?'Online':'Offline'}}</p><button v-if="selectedPartner.roomId&&selectedPartner.roomId!==room?.roomId" class="button full" @click="join(selectedPartner.roomId);dialog=null">Join room</button><button class="button secondary full" @click="share">Invite to watch</button></template><template v-else><p>{{room?members.length+' watching together':'Your next watch night starts here.'}}</p><div class="settings-members"><div v-for="m in members" :key="m.socketId"><span class="avatar small">{{m.avatar}}</span><strong>{{m.name}}{{m.id===profile.id?' (you)':''}}</strong><Headphones v-if="m.voice" :size="18"/></div></div><div class="party-settings"><button @click="edit"><span class="avatar small">{{profile.avatar}}</span><span>Edit profile</span><ChevronRight :size="18"/></button><button role="switch" :aria-checked="showAvatars" @click="showAvatars=!showAvatars"><Users :size="21"/><span>Show avatars</span><span class="settings-toggle" :class="{on:showAvatars}"/></button><button :disabled="!room" @click="active?voice.toggleMute():voice.start()"><MicOff v-if="!active||muted" :size="21"/><Mic v-else :size="21"/><span>{{active?(muted?'Unmute microphone':'Mute microphone'):'Join voice chat'}}</span></button><button v-if="active" @click="voice.stop"><LogOut :size="21"/><span>Leave voice chat</span></button><button @click="share"><Plus :size="21"/><span>Invite friends</span><ChevronRight :size="18"/></button></div><p v-if="voiceError" class="form-error" role="alert">{{voiceError}}</p></template></template>
   <template v-else-if="dialog==='install'"><span class="modal-icon"><MonitorPlay :size="27"/></span><h2>A home for movie night.</h2><p>Add Afterglow to your Home Screen for a full-screen app experience.</p><ol class="install-steps"><li>Open this app in Safari on your iPhone.</li><li>Tap the Share button.</li><li>Choose “Add to Home Screen”, then tap Add.</li></ol><p class="modal-hint">On Android, use Install app in your browser menu. Watching together needs an internet connection.</p></template>
   <template v-else><span class="profile-preview avatar">{{editAvatar}}</span><h2>Make yourself at home.</h2><p>A familiar face for your next watch night.</p><form @submit.prevent="save"><label for="guest-name">Your name</label><input id="guest-name" v-model="editName" maxlength="24" required/><label>Pick your avatar</label><div class="avatar-picker"><button v-for="a in avatars" :class="{chosen:editAvatar===a}" type="button" :aria-label="'Select avatar '+a" @click="editAvatar=a">{{a}}</button></div><button class="button full" type="submit">Save profile <Check :size="17"/></button></form><button class="button secondary full install-button" @click="install"><Plus :size="18"/> Add to Home Screen</button><button class="text-button new-guest" @click="newGuest">Use a new guest identity</button><span class="modal-hint">A new identity clears your saved partners on this browser.</span></template>
  </section></div>
 </div>
</template>
